Repository juliencrn/usehooks-ts, pull requests merged in 2024-01, with the labels that each got.

#383 Removed the need of commenting out useEffect deps
  .changeset/calm-stingrays-lick.md
  packages/usehooks-ts/src/useMediaQuery/useMediaQuery.ts
Labels: enhancement

#367 test: add unit tests on useFetch.
  .changeset/lemon-apricots-smell.md
  packages/usehooks-ts/src/useFetch/useFetch.test.ts
Labels: enhancement

#358 fix(useCopyToClipboard): added useCallback to 'copy' to avoid rerendering
  .changeset/sweet-mangos-sell.md
  packages/usehooks-ts/src/useCopyToClipboard/useCopyToClipboard.ts
Labels: bug

#435 🐛 Fix use storage hydration mismatch
  .changeset/chilled-boats-tease.md
  packages/usehooks-ts/src/useLocalStorage/useLocalStorage.ts
  packages/usehooks-ts/src/useReadLocalStorage/useReadLocalStorage.ts
  packages/usehooks-ts/src/useSessionStorage/useSessionStorage.ts
Labels: bug

#436 🐛 make useLocalStorage and useSessionStorage compliant with useState (fixes #204 with #242 by @valyrie97)
  .changeset/lovely-mayflies-cough.md
  packages/usehooks-ts/src/useLocalStorage/useLocalStorage.test.ts
  packages/usehooks-ts/src/useLocalStorage/useLocalStorage.ts
  packages/usehooks-ts/src/useSessionStorage/useSessionStorage.test.ts
  packages/usehooks-ts/src/useSessionStorage/useSessionStorage.ts
Labels: bug

#437 🐛 Prevent unrelated storage keys from being updated unexpectedly
  .changeset/light-kids-approve.md
  packages/usehooks-ts/src/useLocalStorage/useLocalStorage.test.ts
  packages/usehooks-ts/src/useLocalStorage/useLocalStorage.ts
  packages/usehooks-ts/src/useSessionStorage/useSessionStorage.test.ts
  packages/usehooks-ts/src/useSessionStorage/useSessionStorage.ts
Labels: bug

#439 Feature/add optional serialization to use storage
  .changeset/eighty-experts-hear.md
  .changeset/young-shirts-share.md
  packages/usehooks-ts/src/useLocalStorage/useLocalStorage.md
  packages/usehooks-ts/src/useLocalStorage/useLocalStorage.test.ts
  packages/usehooks-ts/src/useLocalStorage/useLocalStorage.ts
  packages/usehooks-ts/src/useReadLocalStorage/useReadLocalStorage.ts
  packages/usehooks-ts/src/useSessionStorage/useSessionStorage.md
  packages/usehooks-ts/src/useSessionStorage/useSessionStorage.test.ts
  packages/usehooks-ts/src/useSessionStorage/useSessionStorage.ts
Labels: bug, enhancement, help wanted

#446 ♻️ Extract some mocks to reuse them
  packages/usehooks-ts/mocks/index.ts
  packages/usehooks-ts/src/useDarkMode/useDarkMode.test.ts
  packages/usehooks-ts/src/useLocalStorage/useLocalStorage.test.ts
  packages/usehooks-ts/src/useSessionStorage/useSessionStorage.test.ts
Labels: enhancement

#447 ⬆️ Upgrade dependencies & fix eslint config
  apps/www/package.json
  packages/eslint-config-custom/package.json
  packages/usehooks-ts/.eslintrc.js
  packages/usehooks-ts/package.json
  pnpm-lock.yaml
Labels: bug

#445 🐛 Fix hydration issues in both useScreen and useMediaQuery
  .changeset/witty-spiders-explode.md
  packages/usehooks-ts/src/useMediaQuery/useMediaQuery.ts
  packages/usehooks-ts/src/useScreen/useScreen.ts
Labels: bug

#302 ⬆️ Upgrade to react 18, latest @testing-library and migrate to vitest
  .changeset/happy-flies-count.md
  .changeset/strange-schools-battle.md
  packages/eslint-config-custom/.eslintrc.js
  packages/eslint-config-custom/package.json
  packages/usehooks-ts/jest.config.js
  packages/usehooks-ts/package.json
  packages/usehooks-ts/src/useBoolean/useBoolean.test.ts
  packages/usehooks-ts/src/useCopyToClipboard/useCopyToClipboard.test.ts
  packages/usehooks-ts/src/useCountdown/useCountdown.test.ts
  packages/usehooks-ts/src/useCounter/useCounter.test.ts
  packages/usehooks-ts/src/useDarkMode/useDarkMode.test.ts
  packages/usehooks-ts/src/useDebounce/useDebounce.test.ts
  packages/usehooks-ts/src/useDocumentTitle/useDocumentTitle.test.ts
  packages/usehooks-ts/src/useEffectOnce/useEffectOnce.test.ts
  packages/usehooks-ts/src/useElementSize/useElementSize.test.ts
  packages/usehooks-ts/src/useEventListener/useEventListener.test.ts
  packages/usehooks-ts/src/useFetch/useFetch.test.ts
  packages/usehooks-ts/src/useHover/useHover.test.ts
  packages/usehooks-ts/src/useInterval/useInterval.test.ts
  packages/usehooks-ts/src/useIsClient/useIsClient.test.ts
  packages/usehooks-ts/src/useIsFirstRender/useIsFirstRender.test.ts
  packages/usehooks-ts/src/useIsMounted/useIsMounted.test.ts
  packages/usehooks-ts/src/useLocalStorage/useLocalStorage.test.ts
  packages/usehooks-ts/src/useMap/useMap.test.ts
  packages/usehooks-ts/src/useReadLocalStorage/useReadLocalStorage.test.ts
  packages/usehooks-ts/src/useSessionStorage/useSessionStorage.test.ts
  packages/usehooks-ts/src/useStep/useStep.test.ts
  packages/usehooks-ts/src/useTimeout/useTimeout.test.ts
  packages/usehooks-ts/src/useToggle/useToggle.test.ts
  packages/usehooks-ts/src/useUpdateEffect/useUpdateEffect.test.ts
  packages/usehooks-ts/src/useWindowSize/useWindowSize.test.ts
  packages/usehooks-ts/tests/mocks.ts
  packages/usehooks-ts/tests/setup.ts
  packages/usehooks-ts/tsconfig.json
  packages/usehooks-ts/turbo/generators/templates/hook/hook.test.ts.hbs
  packages/usehooks-ts/vite.config.mts
  pnpm-lock.yaml
Labels: enhancement

#443 ✨ Feature: Create `useDebounceCallback` and `useDebounceValue` to replace legacy `useDebounce`
  .changeset/calm-socks-repeat.md
  .changeset/fifty-seahorses-grow.md
  .changeset/rotten-singers-punch.md
  .changeset/silent-mangos-live.md
  packages/usehooks-ts/package.json
  packages/usehooks-ts/src/index.ts
  packages/usehooks-ts/src/useDebounce/useDebounce.md
  packages/usehooks-ts/src/useDebounce/useDebounce.ts
  packages/usehooks-ts/src/useDebounceCallback/index.ts
  packages/usehooks-ts/src/useDebounceCallback/useDebounceCallback.demo.tsx
  packages/usehooks-ts/src/useDebounceCallback/useDebounceCallback.md
  packages/usehooks-ts/src/useDebounceCallback/useDebounceCallback.test.ts
  packages/usehooks-ts/src/useDebounceCallback/useDebounceCallback.ts
  packages/usehooks-ts/src/useDebounceValue/index.ts
  packages/usehooks-ts/src/useDebounceValue/useDebounceValue.demo.tsx
  packages/usehooks-ts/src/useDebounceValue/useDebounceValue.md
  packages/usehooks-ts/src/useDebounceValue/useDebounceValue.test.ts
  packages/usehooks-ts/src/useDebounceValue/useDebounceValue.ts
  packages/usehooks-ts/src/useUnmount/index.ts
  packages/usehooks-ts/src/useUnmount/useUnmount.demo.tsx
  packages/usehooks-ts/src/useUnmount/useUnmount.md
  packages/usehooks-ts/src/useUnmount/useUnmount.test.ts
  packages/usehooks-ts/src/useUnmount/useUnmount.ts
  pnpm-lock.yaml
Labels: feature request

#344 feat(useTernaryDarkMode): Add `defaultValue` parameter
  .changeset/neat-books-shave.md
  .changeset/ten-lions-film.md
  packages/usehooks-ts/src/useDarkMode/useDarkMode.test.ts
  packages/usehooks-ts/src/useDarkMode/useDarkMode.ts
  packages/usehooks-ts/src/useTernaryDarkMode/useTernaryDarkMode.md
  packages/usehooks-ts/src/useTernaryDarkMode/useTernaryDarkMode.test.ts
  packages/usehooks-ts/src/useTernaryDarkMode/useTernaryDarkMode.ts
  packages/usehooks-ts/src/useUnmount/useUnmount.test.ts
Labels: enhancement

#451 ✨ Feature: declarative SSR
  .changeset/angry-otters-kick.md
  .changeset/gorgeous-donuts-grin.md
  packages/usehooks-ts/src/useDarkMode/useDarkMode.md
  packages/usehooks-ts/src/useDarkMode/useDarkMode.ts
  packages/usehooks-ts/src/useElementSize/useElementSize.md
  packages/usehooks-ts/src/useElementSize/useElementSize.ts
  packages/usehooks-ts/src/useLocalStorage/useLocalStorage.md
  packages/usehooks-ts/src/useLocalStorage/useLocalStorage.ts
  packages/usehooks-ts/src/useMediaQuery/useMediaQuery.md
  packages/usehooks-ts/src/useMediaQuery/useMediaQuery.ts
  packages/usehooks-ts/src/useReadLocalStorage/useReadLocalStorage.md
  packages/usehooks-ts/src/useReadLocalStorage/useReadLocalStorage.ts
  packages/usehooks-ts/src/useScreen/useScreen.md
  packages/usehooks-ts/src/useScreen/useScreen.ts
  packages/usehooks-ts/src/useSessionStorage/useSessionStorage.md
  packages/usehooks-ts/src/useSessionStorage/useSessionStorage.ts
  packages/usehooks-ts/src/useTernaryDarkMode/useTernaryDarkMode.demo.tsx
  packages/usehooks-ts/src/useTernaryDarkMode/useTernaryDarkMode.md
  packages/usehooks-ts/src/useTernaryDarkMode/useTernaryDarkMode.ts
  packages/usehooks-ts/src/useWindowSize/useWindowSize.demo.tsx
  packages/usehooks-ts/src/useWindowSize/useWindowSize.md
  packages/usehooks-ts/src/useWindowSize/useWindowSize.ts
Labels: bug, documentation, enhancement

#353 Add useClickAnyWhere tests
  packages/usehooks-ts/src/useClickAnyWhere/useClickAnyWhere.test.ts
Labels: enhancement
