Repository juliencrn/usehooks-ts, pull requests merged in 2024-02, with the labels that each got.

#346 ✨ feat: add an option to reset to default document title on unmount for useDocumentTitle
  .changeset/nervous-shrimps-sing.md
  packages/usehooks-ts/src/useDocumentTitle/useDocumentTitle.md
  packages/usehooks-ts/src/useDocumentTitle/useDocumentTitle.test.ts
  packages/usehooks-ts/src/useDocumentTitle/useDocumentTitle.ts
Labels: enhancement

#462 Feature/verbatim module syntax
  .changeset/gold-paws-compare.md
  .vscode/settings.json
  apps/www/src/app/(docs)/react-hook/[slug]/page.tsx
  apps/www/src/components/icons.tsx
  apps/www/src/components/main-nav.tsx
  apps/www/src/components/mobile-nav.tsx
  apps/www/src/components/remote-mdx.tsx
  apps/www/src/components/sidebar-nav.tsx
  apps/www/src/components/theme-provider.tsx
  apps/www/src/components/ui/button.tsx
  apps/www/src/components/ui/components.tsx
  apps/www/src/config/docs.ts
  apps/www/src/config/marketing.ts
  apps/www/src/config/site.ts
  apps/www/src/lib/mdx.ts
  apps/www/src/lib/utils.ts
  packages/eslint-config-custom/.eslintrc.js
  packages/usehooks-ts/.eslintrc.js
  packages/usehooks-ts/src/useBoolean/useBoolean.ts
  packages/usehooks-ts/src/useCountdown/useCountdown.demo.tsx
  packages/usehooks-ts/src/useCounter/useCounter.ts
  packages/usehooks-ts/src/useDebounce/useDebounce.demo.tsx
  packages/usehooks-ts/src/useDebounceValue/useDebounceValue.ts
  packages/usehooks-ts/src/useEffectOnce/useEffectOnce.ts
  packages/usehooks-ts/src/useEventListener/useEventListener.test.ts
  packages/usehooks-ts/src/useEventListener/useEventListener.ts
  packages/usehooks-ts/src/useFetch/useFetch.demo.tsx
  packages/usehooks-ts/src/useFetch/useFetch.ts
  packages/usehooks-ts/src/useHover/useHover.test.ts
  packages/usehooks-ts/src/useHover/useHover.ts
  packages/usehooks-ts/src/useImageOnLoad/useImageOnLoad.demo.tsx
  packages/usehooks-ts/src/useImageOnLoad/useImageOnLoad.ts
  packages/usehooks-ts/src/useIntersectionObserver/useIntersectionObserver.ts
  packages/usehooks-ts/src/useInterval/useInterval.demo.tsx
  packages/usehooks-ts/src/useLocalStorage/useLocalStorage.ts
  packages/usehooks-ts/src/useLockedBody/useLockedBody.demo.tsx
  packages/usehooks-ts/src/useMap/useMap.demo.tsx
  packages/usehooks-ts/src/useMap/useMap.test.ts
  packages/usehooks-ts/src/useOnClickOutside/useOnClickOutside.ts
  packages/usehooks-ts/src/useSessionStorage/useSessionStorage.ts
  packages/usehooks-ts/src/useStep/useStep.ts
  packages/usehooks-ts/src/useTernaryDarkMode/useTernaryDarkMode.demo.tsx
  packages/usehooks-ts/src/useTernaryDarkMode/useTernaryDarkMode.ts
  packages/usehooks-ts/src/useToggle/useToggle.ts
  packages/usehooks-ts/src/useUpdateEffect/useUpdateEffect.ts
Labels: enhancement

#374 fix: to not call handler when disconnected target's event occurs
  .changeset/eight-buses-rush.md
  packages/usehooks-ts/src/useOnClickOutside/useOnClickOuside.test.ts
  packages/usehooks-ts/src/useOnClickOutside/useOnClickOutside.ts
Labels: bug

#354 fix: useScript failed to remove script from cache when passing `removeOnUnmount` prop
  .changeset/giant-shrimps-draw.md
  packages/usehooks-ts/src/useScript/useScript.test.ts
  packages/usehooks-ts/src/useScript/useScript.ts
Labels: bug

#464 ✨ Improve useIntersectionObserver
  .changeset/polite-pianos-live.md
  packages/usehooks-ts/src/useIntersectionObserver/useIntersectionObserver.demo.tsx
  packages/usehooks-ts/src/useIntersectionObserver/useIntersectionObserver.md
  packages/usehooks-ts/src/useIntersectionObserver/useIntersectionObserver.ts
Labels: bug, enhancement

#472 🐛 Fix: SSR hooks now fallback with default or initial value instead of `undefined`
  .changeset/flat-radios-notice.md
  packages/usehooks-ts/src/useDarkMode/useDarkMode.test.ts
  packages/usehooks-ts/src/useDarkMode/useDarkMode.ts
  packages/usehooks-ts/src/useElementSize/useElementSize.demo.tsx
  packages/usehooks-ts/src/useElementSize/useElementSize.md
  packages/usehooks-ts/src/useElementSize/useElementSize.test.ts
  packages/usehooks-ts/src/useElementSize/useElementSize.ts
  packages/usehooks-ts/src/useLocalStorage/useLocalStorage.demo.tsx
  packages/usehooks-ts/src/useLocalStorage/useLocalStorage.md
  packages/usehooks-ts/src/useLocalStorage/useLocalStorage.ts
  packages/usehooks-ts/src/useMediaQuery/useMediaQuery.ts
  packages/usehooks-ts/src/useScreen/useScreen.demo.tsx
  packages/usehooks-ts/src/useScreen/useScreen.md
  packages/usehooks-ts/src/useScreen/useScreen.ts
  packages/usehooks-ts/src/useSessionStorage/useSessionStorage.md
  packages/usehooks-ts/src/useSessionStorage/useSessionStorage.ts
  packages/usehooks-ts/src/useTernaryDarkMode/useTernaryDarkMode.ts
  packages/usehooks-ts/src/useWindowSize/useWindowSize.demo.tsx
  packages/usehooks-ts/src/useWindowSize/useWindowSize.ts
Labels: bug

#494 Fix setMatches hook in useMediaQuery by defining getMatches before use
  .changeset/real-foxes-fold.md
  packages/usehooks-ts/src/useMediaQuery/useMediaQuery.ts
Labels: bug

#479 ✨ Feature: add `useScrollLock` hook
  .changeset/eight-wombats-count.md
  .changeset/poor-spiders-scream.md
  apps/www/src/components/mobile-nav.tsx
  packages/usehooks-ts/src/index.ts
  packages/usehooks-ts/src/useLockedBody/useLockedBody.ts
  packages/usehooks-ts/src/useScrollLock/index.ts
  packages/usehooks-ts/src/useScrollLock/useScrollLock.demo.tsx
  packages/usehooks-ts/src/useScrollLock/useScrollLock.md
  packages/usehooks-ts/src/useScrollLock/useScrollLock.test.ts
  packages/usehooks-ts/src/useScrollLock/useScrollLock.ts
  scripts/updateReadme.mjs
  scripts/updateTestingIssue.mjs
Labels: feature request

#502 🏗️ Move the full workspace to ES Module
  .changeset/tame-news-live.md
  README.md
  apps/www/.eslintrc.cjs
  apps/www/env.js
  apps/www/next-sitemap.config.js
  apps/www/next.config.js
  apps/www/package.json
  apps/www/postcss.config.cjs
  apps/www/tailwind.config.js
  apps/www/tsconfig.json
  package.json
  packages/eslint-config-custom/.eslintrc.cjs
  packages/eslint-config-custom/index.cjs
  packages/eslint-config-custom/index.js
  packages/eslint-config-custom/package.json
  packages/usehooks-ts/.eslintrc.cjs
  packages/usehooks-ts/README.md
  packages/usehooks-ts/package.json
  packages/usehooks-ts/vitest.config.ts
  pnpm-lock.yaml
  scripts/copyHooks.js
  scripts/updateReadme.js
  scripts/updateTestingIssue.js
  scripts/utils.js
  turbo/generators/config.cts
  turbo/generators/templates/hook/hook.demo.tsx.hbs
  turbo/generators/templates/hook/hook.mdx.hbs
  turbo/generators/templates/hook/hook.test.ts.hbs
  turbo/generators/templates/hook/hook.ts.hbs
  turbo/generators/templates/hook/index.ts.hbs
  turbo/generators/templates/index.ts.hbs
Labels: V3

#503 🔥 Remove deprecated hooks and co
  .changeset/clean-lies-laugh.md
  apps/www/src/app/(docs)/react-hook/[slug]/page.tsx
  apps/www/src/components/table-of-content.tsx
  apps/www/src/lib/mdx.ts
  apps/www/src/types/index.d.ts
  packages/usehooks-ts/src/index.ts
  packages/usehooks-ts/src/useCountdown/useCountdown.ts
  packages/usehooks-ts/src/useDarkMode/useDarkMode.test.ts
  packages/usehooks-ts/src/useDarkMode/useDarkMode.ts
  packages/usehooks-ts/src/useDebounce/index.ts
  packages/usehooks-ts/src/useDebounce/useDebounce.demo.tsx
  packages/usehooks-ts/src/useDebounce/useDebounce.md
  packages/usehooks-ts/src/useDebounce/useDebounce.test.ts
  packages/usehooks-ts/src/useDebounce/useDebounce.ts
  packages/usehooks-ts/src/useEffectOnce/index.ts
  packages/usehooks-ts/src/useEffectOnce/useEffectOnce.demo.tsx
  packages/usehooks-ts/src/useEffectOnce/useEffectOnce.md
  packages/usehooks-ts/src/useEffectOnce/useEffectOnce.test.ts
  packages/usehooks-ts/src/useEffectOnce/useEffectOnce.ts
  packages/usehooks-ts/src/useElementSize/index.ts
  packages/usehooks-ts/src/useElementSize/useElementSize.demo.tsx
  packages/usehooks-ts/src/useElementSize/useElementSize.md
  packages/usehooks-ts/src/useElementSize/useElementSize.test.ts
  packages/usehooks-ts/src/useElementSize/useElementSize.ts
  packages/usehooks-ts/src/useFetch/index.ts
  packages/usehooks-ts/src/useFetch/useFetch.demo.tsx
  packages/usehooks-ts/src/useFetch/useFetch.md
  packages/usehooks-ts/src/useFetch/useFetch.test.ts
  packages/usehooks-ts/src/useFetch/useFetch.ts
  packages/usehooks-ts/src/useImageOnLoad/index.ts
  packages/usehooks-ts/src/useImageOnLoad/useImageOnLoad.demo.tsx
  packages/usehooks-ts/src/useImageOnLoad/useImageOnLoad.md
  packages/usehooks-ts/src/useImageOnLoad/useImageOnLoad.ts
  packages/usehooks-ts/src/useIntersectionObserver/useIntersectionObserver.ts
  packages/usehooks-ts/src/useIsFirstRender/index.ts
  packages/usehooks-ts/src/useIsFirstRender/useIsFirstRender.demo.tsx
  packages/usehooks-ts/src/useIsFirstRender/useIsFirstRender.md
  packages/usehooks-ts/src/useIsFirstRender/useIsFirstRender.test.ts
  packages/usehooks-ts/src/useIsFirstRender/useIsFirstRender.ts
  packages/usehooks-ts/src/useLockedBody/index.ts
  packages/usehooks-ts/src/useLockedBody/useLockedBody.demo.tsx
  packages/usehooks-ts/src/useLockedBody/useLockedBody.md
  packages/usehooks-ts/src/useLockedBody/useLockedBody.ts
  packages/usehooks-ts/src/useMediaQuery/useMediaQuery.ts
  packages/usehooks-ts/src/useSsr/index.ts
  packages/usehooks-ts/src/useSsr/useSsr.ts
  packages/usehooks-ts/src/useTernaryDarkMode/useTernaryDarkMode.test.ts
  packages/usehooks-ts/src/useTernaryDarkMode/useTernaryDarkMode.ts
  packages/usehooks-ts/src/useUpdateEffect/index.ts
  packages/usehooks-ts/src/useUpdateEffect/useUpdateEffect.demo.tsx
  packages/usehooks-ts/src/useUpdateEffect/useUpdateEffect.md
  packages/usehooks-ts/src/useUpdateEffect/useUpdateEffect.test.ts
  packages/usehooks-ts/src/useUpdateEffect/useUpdateEffect.ts
  scripts/copyHooks.js
  scripts/updateReadme.js
  scripts/updateTestingIssue.js
Labels: V3
